development:
  adapter: postgresql
  username: 'aberlin'
  database: 'retrospective_dev'

test:
  adapter: postgresql
  username: 'aberlin'
  database: 'retrospective_test'

production:
  adapter: postgresql
  database: 'retrospective_prod'
